# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name:  nexus
#   namespace: nexus
#   labels:
#     app:  nexus
# spec:
#   selector:
#     matchLabels:
#       app: nexus
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app:  nexus
#     spec:
#       # initContainers:
#         # Init containers are exactly like regular containers, except:
#           # - Init containers always run to completion.
#           # - Each init container must complete successfully before the next one starts.
#       securityContext:
#         fsGroup: 200
#       containers:
#       - name:  nexus
#         image:  sonatype/nexus3:latest
#         ports:
#         - containerPort: 8081
#         volumeMounts:
#         - name: nexus-volume
#           mountPath: /nexus-data
#       volumes:
#         - name: nexus-volume
#           persistentVolumeClaim:
#             claimName: nexus-pvc



apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      initContainers:
        - name: chown-nexusdata-owner-to-nexus
          image: busybox:1.34.1
          command: [ "/bin/sh","-c" ]
          args: [ "chown -R 200:200 /nexus-data" ]
          volumeMounts:
            - name: nexus-volume
              mountPath: /nexus-data
      containers:
        - image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          name: nexus
          env:
            - name: NEXUS_SEARCH_INDEX_REBUILD_ON_STARTUP
              value: "true"
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms1g -Xmx2g -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
          resources:
            requests:
              cpu: "0.25"
              memory: "512M"
            limits:
              cpu: "0.5"
              memory: "2304M"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-volume
              mountPath: /nexus-data
          securityContext:
            runAsUser: 200
      volumes:
        - name: nexus-volume
          persistentVolumeClaim:
            claimName: nexus-pvc