apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
spec:
  storageClassName: local-storage-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi